Repository ZenBit-Tech/sunny-bunnies_be, pull requests merged in 2024-06, with the labels that each got.

#3 Fix/template
  package-lock.json
  package.json
  src/app.module.ts
  src/common/configs/typeorm-data-source.config.ts
  src/common/configs/typeorm.config.ts
  src/entities/index.ts
  src/entities/test.entity.ts
  src/main.ts
  src/migrations/1716554605592-cats.ts
  src/migrations/1716556299086-cats-autogenerated-id.ts
  src/migrations/1716752850275-test-entity.ts
  src/modules/cats/cat.entity.ts
  src/modules/cats/cats.controller.ts
  src/modules/cats/cats.module.ts
  src/modules/cats/cats.repository.ts
  src/modules/cats/cats.service.ts
  src/modules/cats/dto/create-cat.dto.ts
  src/modules/test/dto/create-test-entity.dto.ts
  src/modules/test/dto/index.ts
  src/modules/test/test.controller.ts
  src/modules/test/test.module.ts
  src/modules/test/test.repository.ts
  src/modules/test/test.service.ts
Labels: enhancement

#1 Feat: SB-23 Sign-up backend
  .env.example
  .eslintrc.js
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/common/configs/index.ts
  src/common/constants/constants.ts
  src/common/decorators/get-user.decorator.ts
  src/common/decorators/index.ts
  src/common/decorators/public-route.decorator.ts
  src/common/interceptors/index.ts
  src/common/interceptors/transformation.interceptor.ts
  src/common/types/auth-payload-token.type.ts
  src/common/types/auth-response.type.ts
  src/common/types/auth-tokens.type.ts
  src/common/types/index.ts
  src/common/types/payload-token.type.ts
  src/entities/index.ts
  src/entities/user.entity.ts
  src/main.ts
  src/migrations/1716804683137-create-user-entity.ts
  src/migrations/1716808511079-add-user-entity-name.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/auth-generate-access.dto.ts
  src/modules/auth/dto/auth-sign-up.dto.ts
  src/modules/auth/dto/index.ts
  src/modules/auth/encrypt.service.ts
  src/modules/auth/guards/index.ts
  src/modules/auth/guards/jwt-auth.guard.ts
  src/modules/auth/token.service.ts
  src/modules/users/dto/create-user.dto.ts
  src/modules/users/dto/index.ts
  src/modules/users/users.module.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.ts
Labels: enhancement

#4 Feat: SB-26 Sign-In logic
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/auth-sign-in.dto.ts
  src/modules/auth/dto/index.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
Labels: enhancement

#8 Feature sb 29 home page products
  README.md
  package.json
  src/app.module.ts
  src/common/configs/typeorm.config.ts
  src/common/constants/constants.ts
  src/common/enums/index.ts
  src/entities/brand.entity.ts
  src/entities/category.entity.ts
  src/entities/colors.entity.ts
  src/entities/image.entity.ts
  src/entities/index.ts
  src/entities/material.entity.ts
  src/entities/product.entity.ts
  src/entities/size.entity.ts
  src/entities/style.entity.ts
  src/migrations/1717419028301-color-entity.ts
  src/migrations/1717425420610-category-entity.ts
  src/migrations/1717426044029-size-entity.ts
  src/migrations/1717426105363-style-entity.ts
  src/migrations/1717426174093-image-entity.ts
  src/migrations/1717426472469-brand-entity.ts
  src/migrations/1717426524891-material-entity.ts
  src/migrations/1717426580703-product-entity.ts
  src/modules/products/dto/get-products-query.dto.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.module.ts
  src/modules/products/products.repository.ts
  src/modules/products/products.service.ts
  src/seeds/combined-seeder.ts
  src/seeds/data-source.ts
  src/seeds/seed-data.ts
  tsconfig.json
Labels: enhancement

#6 Feat: SB-24 add google sign up
  .env.example
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/google-auth-sing-up.dto.ts
  src/modules/auth/dto/index.ts
  src/modules/auth/encrypt.service.ts
Labels: enhancement

#13 Feature sb 26 product filter
  package-lock.json
  package.json
  src/common/constants/constants.ts
  src/common/enums/index.ts
  src/entities/product.entity.ts
  src/migrations/1717419028301-color-entity.ts
  src/migrations/1717425420610-category-entity.ts
  src/migrations/1717426044029-size-entity.ts
  src/migrations/1717426105363-style-entity.ts
  src/migrations/1717426174093-image-entity.ts
  src/migrations/1717426472469-brand-entity.ts
  src/migrations/1717426524891-material-entity.ts
  src/migrations/1717426580703-product-entity.ts
  src/modules/products/dto/get-products-query.dto.ts
  src/modules/products/products.repository.ts
Labels: enhancement

#11 fix: changed enum import
  src/common/enums/index.ts
  src/entities/product.entity.ts
  src/migrations/1717419028301-color-entity.ts
  src/migrations/1717425420610-category-entity.ts
  src/migrations/1717426044029-size-entity.ts
  src/migrations/1717426105363-style-entity.ts
  src/migrations/1717426174093-image-entity.ts
  src/migrations/1717426472469-brand-entity.ts
  src/migrations/1717426524891-material-entity.ts
  src/migrations/1717426580703-product-entity.ts
Labels: enhancement

#12 Feat: SB-15 sign in with google
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
Labels: enhancement

#7 Feat: SB-61 OTP code functionality
  .env.example
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  src/app.module.ts
  src/common/configs/index.ts
  src/common/configs/nodemailer.config.ts
  src/common/templates/verify-email.hbs
  src/common/types/auth-response.type.ts
  src/common/types/index.ts
  src/common/types/otp-code-payload-token.type.ts
  src/entities/product.entity.ts
  src/entities/user.entity.ts
  src/migrations/1717159865380-user-otp-verification.ts
  src/migrations/1717419028301-color-entity.ts
  src/migrations/1717425420610-category-entity.ts
  src/migrations/1717426044029-size-entity.ts
  src/migrations/1717426105363-style-entity.ts
  src/migrations/1717426174093-image-entity.ts
  src/migrations/1717426472469-brand-entity.ts
  src/migrations/1717426524891-material-entity.ts
  src/migrations/1717426580703-product-entity.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/auth-verify-email.dto.ts
  src/modules/auth/dto/auth-verify-otp.dto.ts
  src/modules/auth/dto/index.ts
  src/modules/auth/guards/auth-guard.service.ts
  src/modules/auth/guards/index.ts
  src/modules/auth/token.service.ts
  src/modules/products/dto/get-products-query.dto.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.module.ts
  src/modules/products/products.repository.ts
  src/modules/products/products.service.ts
  src/modules/test/test.controller.ts
  src/modules/test/test.module.ts
  src/modules/test/test.repository.ts
  src/modules/test/test.service.ts
  src/modules/users/dto/index.ts
  src/modules/users/dto/update-user.dto.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.ts
  src/seeds/combined-seeder.ts
  src/seeds/data-source.ts
  src/seeds/seed-data.ts
  tsconfig.json
Labels: enhancement

#18 Fix: path function, removed tablename enum
  src/common/configs/typeorm-data-source.config.ts
  src/common/configs/typeorm.config.ts
  src/common/enums/index.ts
  src/migrations/1717419028301-color-entity.ts
  src/migrations/1717425420610-category-entity.ts
  src/migrations/1717426044029-size-entity.ts
  src/migrations/1717426105363-style-entity.ts
  src/migrations/1717426174093-image-entity.ts
  src/migrations/1717426472469-brand-entity.ts
  src/migrations/1717426524891-material-entity.ts
  src/migrations/1717426580703-product-entity.ts
Labels: enhancement

#19 fix/added tsconfig-paths/register, fixed dublicate creating fk
  src/common/configs/typeorm-data-source.config.ts
  src/common/configs/typeorm.config.ts
  src/migrations/1717426580703-product-entity.ts
  tsconfig.json
Labels: bug

#15 Feat: SB 45 my profile complete form
  README.md
  src/entities/card.entity.ts
  src/entities/index.ts
  src/entities/user-profile.entity.ts
  src/entities/user.entity.ts
  src/migrations/1717426580805-user-details-entity.ts
  src/migrations/1717426580835-user-card-entity.ts
  src/modules/auth/auth.service.ts
  src/modules/users/dto/index.ts
  src/modules/users/dto/user-card.dto.ts
  src/modules/users/dto/user-profile-update.dto.ts
  src/modules/users/dto/user-profile.dto.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.ts
Labels: enhancement

#20 Feature sb 74 public product page
  .eslintrc.js
  .husky/pre-commit
  README.md
  src/common/constants/constants.ts
  src/entities/color.entity.ts
  src/entities/image.entity.ts
  src/entities/index.ts
  src/entities/product-variant.entity.ts
  src/entities/product.entity.ts
  src/entities/user.entity.ts
  src/migrations/1718357671543-product-variants.ts
  src/migrations/1718617062801-add-product-id-to-product-images.ts
  src/migrations/1718618335390-delete-image-id-and-quantity-from-products-table.ts
  src/migrations/1718623765257-add-user-id-to-product-table.ts
  src/migrations/1718627982515-delete-quantity-from-product-table.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.module.ts
  src/modules/products/products.repository.ts
  src/modules/products/products.service.ts
  src/seeds/combined-seeder.ts
  src/seeds/data-source.ts
  src/seeds/seed-data.ts
Labels: enhancement

#21 Feature: sb 49 upload an avatar
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/modules/upload/upload.controller.ts
  src/modules/upload/upload.module.ts
  src/modules/upload/upload.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: documentation, enhancement

#22 Feature sb 66 vendor public profile page
  README.md
  src/app.module.ts
  src/common/enums/index.ts
  src/entities/index.ts
  src/entities/product.entity.ts
  src/entities/user-profile.entity.ts
  src/entities/user.entity.ts
  src/entities/users-rating.entity.ts
  src/entities/users-review.entity.ts
  src/migrations/1718715202519-add-followers-and-rating-tables.ts
  src/migrations/1718801205402-add-users-reviews-table.ts
  src/migrations/1718869023320-add-status-column-to-products.ts
  src/modules/followers/followers.controller.ts
  src/modules/followers/followers.module.ts
  src/modules/followers/followers.repository.ts
  src/modules/followers/followers.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.ts
  src/seeds/combined-seeder.ts
  src/seeds/seed-data.ts
Labels: enhancement

#23 Feature sb 82 admin login
  .env.example
  README.md
  src/migrations/1716804683137-create-user-entity.ts
  src/migrations/1717426580805-user-details-entity.ts
  src/migrations/1717426581221-admin-entity.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
Labels: documentation, enhancement

#26 fix: changed seeds
  src/seeds/seed-data.ts
Labels: bug

#24 fix: migration with dropping image from products
  src/migrations/1718618335390-delete-image-id-and-quantity-from-products-table.ts
Labels: bug

#27 fix: fix migrations
  src/entities/user.entity.ts
  src/migrations/1718715202519-add-rating-tables.ts
  src/migrations/1718801205402-add-users-reviews-table.ts
  src/migrations/1718869023320-add-status-column-to-products.ts
  src/seeds/combined-seeder.ts
  src/seeds/seed-data.ts
Labels: bug

#25 Fix sb-118 fix incorerect behavior of google login
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
Labels: bug

#28 fix: user and follower relation
  package-lock.json
  src/entities/user.entity.ts
  src/seeds/seed-data.ts
Labels: bug

#31 fix: fix filter by color and size
  src/modules/products/products.repository.ts
  src/modules/users/users.service.ts
Labels: bug

#34 Feat sb 74 product preview page
  src/modules/products/products.repository.ts
  src/modules/products/products.service.ts
  src/seeds/combined-seeder.ts
  src/seeds/seed-data.ts
Labels: enhancement

#35 Feature sb 64 vendor/buyer personal page
  src/modules/users/dto/index.ts
  src/modules/users/dto/update-user-and-profile.dto.ts
  src/modules/users/dto/user.dto.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: documentation, enhancement
