Repository ZenBit-Tech/sunny-bunnies_be, pull requests merged in 2024-07, with the labels that each got.

#36 Feature sb 79 list of users for admin
  README.md
  src/app.module.ts
  src/common/templates/block-user.hbs
  src/entities/user.entity.ts
  src/migrations/1719494696693-add-user-status-and-deleted-at.ts
  src/modules/admin/admin.controller.ts
  src/modules/admin/admin.module.ts
  src/modules/admin/dto/index.ts
  src/modules/admin/dto/sort-option.dto.ts
  src/modules/admin/dto/update-status.dto.ts
  src/modules/admin/guard/roles.guard.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/guards/auth-guard.service.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.spec.ts
  src/modules/users/users.service.ts
  src/seeds/seed-data.ts
Labels: enhancement

#40 Fix sb-169 status and update test
  .github/pull_request_template.md
  src/migrations/1718623765257-add-user-id-to-product-table.ts
  src/modules/auth/auth.service.ts
  src/modules/users/user.serivce.spec.ts
  src/modules/users/users.serivce.spec.ts
Labels: bug

#41 Fix sb-174 change sender service
  .env.example
  src/common/configs/nodemailer.config.ts
  src/modules/auth/auth.service.ts
Labels: bug

#42 Feature sb 100 products requests
  src/modules/admin/admin.controller.ts
  src/modules/admin/admin.module.ts
  src/modules/admin/dto/get-admin-products.dto.ts
  src/modules/admin/dto/index.ts
  src/modules/products/dto/get-products-query.dto.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.module.ts
  src/modules/products/products.repository.ts
  src/modules/products/products.service.spec.ts
  src/modules/products/products.service.ts
  src/seeds/seed-data.ts
Labels: documentation, enhancement

#44 Feature sb 173 admin product list
  src/common/templates/delete-product.hbs
  src/entities/product.entity.ts
  src/migrations/1720667511384-newmigration.ts
  src/modules/admin/admin.controller.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.repository.ts
  src/modules/products/products.service.spec.ts
  src/modules/products/products.service.ts
  src/seeds/seed-data.ts
Labels: documentation, enhancement

#45 fix: fix product module
  src/common/configs/typeorm.config.ts
  src/modules/products/products.module.ts
Labels: bug
